-- Run this migration in Supabase SQL Editor before using the new admin workspaces.
-- It relies on the existing public.current_user_is_admin() function used by admin.html.

create extension if not exists pgcrypto;

create table if not exists public.math_requests (
    id bigint generated by default as identity primary key,
    name text,
    email text,
    category_id bigint references public.math_categories(id) on delete set null,
    request_text text not null,
    status text not null default 'pending',
    admin_note text,
    reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.math_requests add column if not exists admin_note text;
alter table public.math_requests add column if not exists reviewed_at timestamptz;
alter table public.math_requests add column if not exists updated_at timestamptz not null default now();

create table if not exists public.document_contributions (
    id uuid primary key default gen_random_uuid(),
    title text not null,
    description text,
    category_id bigint references public.math_categories(id) on delete set null,
    contributor_name text,
    contributor_email text,
    file_path text not null,
    file_name text not null,
    file_size bigint,
    status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
    admin_note text,
    reviewed_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.achievement_evidence (
    id uuid primary key default gen_random_uuid(),
    group_key text not null check (group_key in ('grade10', 'grade12', 'feedback')),
    title text not null,
    student_name text,
    course_name text,
    school_name text,
    result_summary text,
    description text,
    ocr_text text,
    image_path text not null,
    image_name text,
    sort_order integer not null default 0,
    published boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists math_requests_status_created_at_idx
    on public.math_requests (status, created_at desc);
create index if not exists document_contributions_status_created_at_idx
    on public.document_contributions (status, created_at desc);
create index if not exists achievement_evidence_group_sort_idx
    on public.achievement_evidence (group_key, sort_order, created_at desc);

alter table public.math_requests enable row level security;
alter table public.document_contributions enable row level security;
alter table public.achievement_evidence enable row level security;

drop policy if exists "Public can submit material requests" on public.math_requests;
drop policy if exists "Admins can manage material requests" on public.math_requests;
create policy "Public can submit material requests"
    on public.math_requests for insert to anon, authenticated
    with check (status = 'pending');
create policy "Admins can manage material requests"
    on public.math_requests for all to authenticated
    using (public.current_user_is_admin())
    with check (public.current_user_is_admin());

drop policy if exists "Public can submit document contributions" on public.document_contributions;
drop policy if exists "Admins can manage document contributions" on public.document_contributions;
create policy "Public can submit document contributions"
    on public.document_contributions for insert to anon, authenticated
    with check (status = 'pending');
create policy "Admins can manage document contributions"
    on public.document_contributions for all to authenticated
    using (public.current_user_is_admin())
    with check (public.current_user_is_admin());

drop policy if exists "Public can view published achievement evidence" on public.achievement_evidence;
drop policy if exists "Admins can manage achievement evidence" on public.achievement_evidence;
create policy "Public can view published achievement evidence"
    on public.achievement_evidence for select to anon, authenticated
    using (published = true);
create policy "Admins can manage achievement evidence"
    on public.achievement_evidence for all to authenticated
    using (public.current_user_is_admin())
    with check (public.current_user_is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'document-submissions',
    'document-submissions',
    false,
    15728640,
    array['application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'achievement-evidence',
    'achievement-evidence',
    true,
    10485760,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can upload PDF contributions" on storage.objects;
drop policy if exists "Admins can view PDF contributions" on storage.objects;
drop policy if exists "Admins can delete PDF contributions" on storage.objects;
create policy "Public can upload PDF contributions"
    on storage.objects for insert to anon, authenticated
    with check (
        bucket_id = 'document-submissions'
        and lower(storage.extension(name)) = 'pdf'
    );
create policy "Admins can view PDF contributions"
    on storage.objects for select to authenticated
    using (bucket_id = 'document-submissions' and public.current_user_is_admin());
create policy "Admins can delete PDF contributions"
    on storage.objects for delete to authenticated
    using (bucket_id = 'document-submissions' and public.current_user_is_admin());

drop policy if exists "Admins can upload achievement evidence" on storage.objects;
drop policy if exists "Admins can update achievement evidence" on storage.objects;
drop policy if exists "Admins can delete achievement evidence" on storage.objects;
create policy "Admins can upload achievement evidence"
    on storage.objects for insert to authenticated
    with check (bucket_id = 'achievement-evidence' and public.current_user_is_admin());
create policy "Admins can update achievement evidence"
    on storage.objects for update to authenticated
    using (bucket_id = 'achievement-evidence' and public.current_user_is_admin())
    with check (bucket_id = 'achievement-evidence' and public.current_user_is_admin());
create policy "Admins can delete achievement evidence"
    on storage.objects for delete to authenticated
    using (bucket_id = 'achievement-evidence' and public.current_user_is_admin());
